spring.application.name=SpringbootAppMonitoring


management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true
